# Generated by Django 5.2.13 on 2026-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_marca_produto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
