# Generated by Django 5.2.13 on 2026-07-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itemcompra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCompra',
            new_name='ItensCompra',
        ),
    ]
