# Generated by Django 5.2.13 on 2026-08-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_itemcompra_itenscompra'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
