# Generated by Django 5.2.13 on 2026-08-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_categoria_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenscompra',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
